-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.build_components
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    build_id integer NOT NULL,
    "BuildId1" integer NOT NULL,
    component_id integer NOT NULL,
    "ComponentId1" integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    added_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_build_components" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.builds
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    total_price numeric(10, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Draft'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_builds" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    parent_id integer,
    CONSTRAINT "PK_categories" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.components
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    manufacturer character varying(50) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    socket character varying(30) COLLATE pg_catalog."default" NOT NULL,
    form_factor character varying(30) COLLATE pg_catalog."default" NOT NULL,
    memory_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    max_memory integer,
    power_supply integer,
    memory_slots integer,
    max_memory_per_slot integer,
    tdp integer,
    length integer,
    width integer,
    height integer,
    CONSTRAINT "PK_components" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    build_id integer NOT NULL,
    user_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    total_price numeric(10, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT "PK_orders" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    passwordhash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Client'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.build_components
    ADD CONSTRAINT "FK_build_components_builds_BuildId1" FOREIGN KEY ("BuildId1")
    REFERENCES public.builds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_build_components_BuildId1"
    ON public.build_components("BuildId1");


ALTER TABLE IF EXISTS public.build_components
    ADD CONSTRAINT "FK_build_components_builds_build_id" FOREIGN KEY (build_id)
    REFERENCES public.builds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_build_components_build_id"
    ON public.build_components(build_id);


ALTER TABLE IF EXISTS public.build_components
    ADD CONSTRAINT "FK_build_components_components_ComponentId1" FOREIGN KEY ("ComponentId1")
    REFERENCES public.components (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_build_components_ComponentId1"
    ON public.build_components("ComponentId1");


ALTER TABLE IF EXISTS public.build_components
    ADD CONSTRAINT "FK_build_components_components_component_id" FOREIGN KEY (component_id)
    REFERENCES public.components (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_build_components_component_id"
    ON public.build_components(component_id);


ALTER TABLE IF EXISTS public.builds
    ADD CONSTRAINT "FK_builds_users_user_id" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_builds_user_id"
    ON public.builds(user_id);


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT "FK_categories_categories_parent_id" FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_categories_parent_id"
    ON public.categories(parent_id);


ALTER TABLE IF EXISTS public.components
    ADD CONSTRAINT "FK_components_categories_category_id" FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_components_category_id"
    ON public.components(category_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "FK_orders_builds_build_id" FOREIGN KEY (build_id)
    REFERENCES public.builds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_orders_build_id"
    ON public.orders(build_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "FK_orders_users_user_id" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_orders_user_id"
    ON public.orders(user_id);

END;