-- Скрипт создания базы данных PC Builder
-- Сгенерирован на основе C# моделей

BEGIN;

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    description character varying(200),
    parent_id integer,
    CONSTRAINT "PK_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_categories_categories_parent_id" FOREIGN KEY (parent_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(50) NOT NULL,
    full_name character varying(100) DEFAULT ''::character varying,
    email character varying(100) DEFAULT ''::character varying,
    passwordhash text NOT NULL,
    role character varying(20) DEFAULT 'Client'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "ix_users_username"
    ON public.users USING btree
    (username COLLATE pg_catalog."default" ASC NULLS LAST);

CREATE TABLE IF NOT EXISTS public.components
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    manufacturer character varying(50),
    price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    socket character varying(30),
    form_factor character varying(30),
    memory_type character varying(20),
    max_memory integer,
    power_supply integer,
    memory_slots integer,
    max_memory_per_slot integer,
    tdp integer,
    length integer,
    width integer,
    height integer,
    CONSTRAINT "PK_components" PRIMARY KEY (id),
    CONSTRAINT "FK_components_categories_category_id" FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.builds
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    name character varying(100) NOT NULL,
    total_price numeric(10, 2) NOT NULL,
    status character varying(20) DEFAULT 'Draft'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_builds" PRIMARY KEY (id),
    CONSTRAINT "FK_builds_users_user_id" FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.build_components
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    build_id integer NOT NULL,
    component_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    added_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_build_components" PRIMARY KEY (id),
    CONSTRAINT "FK_build_components_builds_build_id" FOREIGN KEY (build_id)
        REFERENCES public.builds (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_build_components_components_component_id" FOREIGN KEY (component_id)
        REFERENCES public.components (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    build_id integer NOT NULL,
    user_id integer NOT NULL,
    status character varying(20) DEFAULT 'Pending'::character varying,
    total_price numeric(10, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT "PK_orders" PRIMARY KEY (id),
    CONSTRAINT "FK_orders_builds_build_id" FOREIGN KEY (build_id)
        REFERENCES public.builds (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_orders_users_user_id" FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

END;
